## Numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
a[::-1]

array([3, 2, 1])

In [6]:
a # 不改变原数组

array([1, 2, 3])

In [7]:
a[0] = -1
a

array([-1,  2,  3])

In [18]:
b = np.zeros([10,10])
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [11]:
c = np.arange(1,9,2)
c

array([1, 3, 5, 7])

In [12]:
d = np.linspace(1,10,10)
d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
e = np.linspace(1,100,10)
e

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [21]:
a = np.arange(0,24)
b = a.reshape(4,6)
b
# a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
b[:3]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [16]:
b[:,:3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [30]:
b[[1,2,0]]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5]])

## broadcast

In [57]:
a = np.arange(1,25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [58]:
a + 1

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [59]:
a * 3

array([[ 3,  6,  9, 12, 15, 18],
       [21, 24, 27, 30, 33, 36],
       [39, 42, 45, 48, 51, 54],
       [57, 60, 63, 66, 69, 72]])

In [34]:
a.shape

(4, 6)

In [40]:
a.size

24

In [4]:
import numpy as np
b = np.arange(1,7).reshape(1,6)
b

array([[1, 2, 3, 4, 5, 6]])

In [49]:
b.shape

(6,)

In [51]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [50]:
a + b

array([[ 2,  4,  6,  8, 10, 12],
       [ 8, 10, 12, 14, 16, 18],
       [14, 16, 18, 20, 22, 24],
       [20, 22, 24, 26, 28, 30]])

In [60]:
a * b

array([[  1,   4,   9,  16,  25,  36],
       [  7,  16,  27,  40,  55,  72],
       [ 13,  28,  45,  64,  85, 108],
       [ 19,  40,  63,  88, 115, 144]])

## 课后作业

谷歌搜索 numpy的broadcast机制，算一下shape为(4,6)和shape为(4,1)能不能相加，相乘呢？


算一下shape为(4,6)和shape为(4,)能不能相加,相乘呢？

## 计算函数 

In [54]:
a = np.linspace(0,1,100)
np.exp(a)

array([1.        , 1.0101522 , 1.02040746, 1.03076684, 1.04123139,
       1.05180218, 1.06248028, 1.07326679, 1.0841628 , 1.09516944,
       1.10628782, 1.11751907, 1.12886434, 1.1403248 , 1.1519016 ,
       1.16359593, 1.17540899, 1.18734197, 1.1993961 , 1.21157261,
       1.22387273, 1.23629773, 1.24884887, 1.26152743, 1.2743347 ,
       1.287272  , 1.30034064, 1.31354196, 1.32687729, 1.34034801,
       1.35395549, 1.36770112, 1.38158629, 1.39561243, 1.40978096,
       1.42409333, 1.43855101, 1.45315546, 1.46790818, 1.48281068,
       1.49786447, 1.51307108, 1.52843208, 1.54394902, 1.5596235 ,
       1.5754571 , 1.59145146, 1.60760818, 1.62392894, 1.64041539,
       1.65706921, 1.6738921 , 1.69088579, 1.70805199, 1.72539247,
       1.742909  , 1.76060336, 1.77847735, 1.7965328 , 1.81477156,
       1.83319548, 1.85180644, 1.87060634, 1.88959711, 1.90878067,
       1.92815899, 1.94773404, 1.96750782, 1.98748235, 2.00765966,
       2.02804182, 2.0486309 , 2.06942901, 2.09043826, 2.11166

In [55]:
np.sin(a),np.cos(a)

(array([0.        , 0.01010084, 0.02020065, 0.03029839, 0.04039305,
        0.05048358, 0.06056897, 0.07064817, 0.08072016, 0.09078392,
        0.10083842, 0.11088263, 0.12091552, 0.13093608, 0.14094328,
        0.1509361 , 0.16091352, 0.17087452, 0.18081808, 0.1907432 ,
        0.20064886, 0.21053404, 0.22039774, 0.23023896, 0.24005668,
        0.24984992, 0.25961766, 0.26935891, 0.27907268, 0.28875797,
        0.2984138 , 0.30803919, 0.31763315, 0.3271947 , 0.33672286,
        0.34621667, 0.35567516, 0.36509735, 0.3744823 , 0.38382904,
        0.39313661, 0.40240408, 0.41163048, 0.42081489, 0.42995636,
        0.43905397, 0.44810678, 0.45711386, 0.46607431, 0.47498721,
        0.48385164, 0.49266671, 0.5014315 , 0.51014514, 0.51880673,
        0.52741539, 0.53597023, 0.54447039, 0.55291499, 0.56130318,
        0.56963411, 0.57790691, 0.58612075, 0.59427479, 0.60236819,
        0.61040014, 0.6183698 , 0.62627638, 0.63411905, 0.64189703,
        0.64960951, 0.65725572, 0.66483486, 0.67